// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: historical_price.sql

package db

import (
	"context"
	"time"
)

const addHistoricalPrice = `-- name: AddHistoricalPrice :one
INSERT INTO historical_price (
    date,
    price,
    instrument
) 
VALUES (?, ?, ?) RETURNING id, date, price, instrument
`

type AddHistoricalPriceParams struct {
	Date       time.Time `json:"date"`
	Price      int64     `json:"price"`
	Instrument string    `json:"instrument"`
}

func (q *Queries) AddHistoricalPrice(ctx context.Context, arg AddHistoricalPriceParams) (HistoricalPrice, error) {
	row := q.db.QueryRowContext(ctx, addHistoricalPrice, arg.Date, arg.Price, arg.Instrument)
	var i HistoricalPrice
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}

const getAllHistoricalPrices = `-- name: GetAllHistoricalPrices :many
SELECT date, price, instrument FROM historical_price
`

type GetAllHistoricalPricesRow struct {
	Date       time.Time `json:"date"`
	Price      int64     `json:"price"`
	Instrument string    `json:"instrument"`
}

func (q *Queries) GetAllHistoricalPrices(ctx context.Context) ([]GetAllHistoricalPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHistoricalPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHistoricalPricesRow
	for rows.Next() {
		var i GetAllHistoricalPricesRow
		if err := rows.Scan(&i.Date, &i.Price, &i.Instrument); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
