// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: historical_prices.sql

package main

import (
	"context"
)

const addHistoricalPrice = `-- name: AddHistoricalPrice :one
INSERT INTO historical_prices (
    date,
    price,
    instrument
) 
VALUES (?, ?, ?) RETURNING id, date, price, instrument
`

type AddHistoricalPriceParams struct {
	Date       int64
	Price      int64
	Instrument string
}

func (q *Queries) AddHistoricalPrice(ctx context.Context, arg AddHistoricalPriceParams) (HistoricalPrice, error) {
	row := q.db.QueryRowContext(ctx, addHistoricalPrice, arg.Date, arg.Price, arg.Instrument)
	var i HistoricalPrice
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}

const getHistoricalPrices = `-- name: GetHistoricalPrices :many
SELECT date, price, instrument FROM historical_prices
`

type GetHistoricalPricesRow struct {
	Date       int64
	Price      int64
	Instrument string
}

func (q *Queries) GetHistoricalPrices(ctx context.Context) ([]GetHistoricalPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, getHistoricalPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoricalPricesRow
	for rows.Next() {
		var i GetHistoricalPricesRow
		if err := rows.Scan(&i.Date, &i.Price, &i.Instrument); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
