// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type HistoricalPrice struct {
	ID         int64     `json:"id"`
	Date       time.Time `json:"date"`
	Price      int64     `json:"price"`
	Instrument string    `json:"instrument"`
}

type User struct {
	ID       int64          `json:"id"`
	UserID   string         `json:"user_id"`
	Username string         `json:"username"`
	UserType string         `json:"user_type"`
	Broker   string         `json:"broker"`
	Email    sql.NullString `json:"email"`
	Name     sql.NullString `json:"name"`
	Password sql.NullString `json:"password"`
}
