// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

import (
	"database/sql"
)

type HistoricalPrice struct {
	ID         int64
	Date       int64
	Price      int64
	Instrument string
}

type Profile struct {
	ID       int64
	UserID   string
	Username string
	UserType string
	Broker   string
	Email    sql.NullString
	Name     sql.NullString
	Password sql.NullString
}
