CREATE TABLE IF NOT EXISTS historical_price (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  date DATE NOT NULL,
  price INTEGER NOT NULL,
  instrument TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    user_type TEXT NOT NULL,
    broker TEXT NOT NULL,
    email TEXT UNIQUE,
    name TEXT,
    password TEXT
);
