CREATE TABLE IF NOT EXISTS historical_price (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  date DATE NOT NULL,
  price INTEGER NOT NULL,
  instrument TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);
